export { default as rightBottomGreen } from "./images/rightBottomGreen.svg";
export { default as rightTopYellow } from "./images/rightTopYellow.svg";
export { default as rightTopGreen } from "./images/rightTopGreen.svg";
export { default as leftTopYellow } from "./images/leftTopYellow.svg";
export { default as leftTopGreen } from "./images/leftTopGreen.svg";
export { default as leftBottomYellow } from "./images/leftBottomYellow.svg";
export { default as HeaderLogo } from "./headerImg/HeaderLogo.svg";
export { default as Person } from "./headerImg/Person.svg"
export { default as Chatting } from "./headerImg/Chatting.svg"
export { default as leftGroup } from "./images/leftGroup.svg";
export { default as rightPolygon } from "./images/rightPolygon.svg";
export { default as rightHalf } from "./images/rightHalf.svg";
export { default as testImg } from "./images/testItem.svg";
export { default as count } from "./icons/count.svg";
